version: "3.8"
services:
  orders:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      SERVICE: orders.js
    env_file: orders.env
    depends_on: [ orders-db ]
  orders-db:
    image: postgres
    restart: always
    env_file: orders.env
    volumes:
      - orders_vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  orders_vol: